# Taps
tap "homebrew/cask"
tap "homebrew/cask-fonts"

# Formulea
brew "bat"
brew "curl"
brew "exa"
brew "httpie"
brew "jq"
brew "just"
brew "lua"
brew "ripgrep"
brew "starship"
brew "stow"
brew "tmux"
brew "wget"
brew "zoxide"

# Casks
cask "alfred"
cask "docker"
cask "drawio"
cask "firefox"
cask "font-caskaydia-cove-nerd-font"
cask "font-hack-nerd-font"
cask "hammerspoon"
cask "insomnia"
cask "jetbrains-toolbox"
cask "karabiner-elements"
cask "libreoffice"
cask "linearmouse"
cask "obsidian"
cask "polypane"
cask "raycast"
cask "vivaldi"

