add_newline = false
format = "$username$hostname$directory$git_branch$git_state$git_status$git_metrics$fill${custom.laravel}$php$rust$nodejs$cmd_duration $jobs $time$line_break$character"

[character]
error_symbol = "[❯](red)"
success_symbol = "[❯](blue)"
vicmd_symbol = "[❮](green)"

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[custom]
[custom.laravel]
command = "jq -r '.packages[] | select(.name == \"laravel/framework\") | .version' composer.lock"
description = "Shows the current Laravel version"
format = "[$symbol $output ]($style)"
style = "bold red"
symbol = "L"
when = "test -d vendor/laravel/framework"

[custom.stunnel]
command = "ps -o etime= -p $(ps aux | grep stunnel | grep -v grep | awk '{print $2}')"
format = "[TUNNEL OPEN for $output]($style)"
style = "red"
when = "ps aux | grep stunnel | grep -v grep"

[directory]
read_only = " "
style = "blue"
truncate_to_repo = false
truncation_length = 4

[fill]
symbol = " "

[git_branch]
format = "[$symbol$branch]($style) "
style = "bright-black"
symbol = " "

[git_metrics]
disabled = false

[git_state]
format = "'([$state( $progress_current/$progress_total)]($style)) '"
style = "bright-black"

[git_status]
style = "cyan"

[jobs]
format = "[$symbol]($style)"
number_threshold = 1
style = "bold red"
symbol = ""

[memory_usage]
symbol = " "

[nodejs]
format = "[$symbol($version )]($style)"

[php]
format = "[$symbol($version )]($style)"

[rust]
format = "[$symbol($version )]($style)"
symbol = " "

[time]
disabled = false
format = "[$time ]($style)"
style = "bold white"

