# Terminal
set-option default-terminal "tmux-256color"
set-option -a terminal-overrides ",alacritty:RGB"

# Sane splitting
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# On the fly reloading
bind-key r \
    source-file ~/.tmux.conf\;\
    display-message "Config reloaded"

# Don't rename windows automatically
set-option -g allow-rename off

# Mouse toggling
bind-key M \
    set-option -g mouse on\;\
    display-message "Mouse: ON"

bind-key m \
    set-option -g mouse off\;\
    display-message "Mouse: OFF"

# Remove the delay when pressing escape
set-option -sg escape-time 0

