{
  imports = [
    ./cli.nix
    ./database.nix
    ./discord.nix
    ./direnv.nix
    ./ffmpeg.nix
    ./fzf.nix
    ./git.nix
    ./kitty.nix
    ./linters.nix
    ./lua.nix
    ./neovim.nix
    ./obsidian.nix
    ./silicon.nix
    ./spotify.nix
    ./starship.nix
    ./wezterm.nix
    ./zoxide.nix
    ./zsh.nix
  ];
}
