# vim:fileencoding=utf-8:foldmethod=marker
editor              ~/.local/share/bob/nvim-bin/nvim

font_family         Hack Nerd Font Mono
bold_font           auto
italic_font         auto
bold_italic_font    auto

font_size           13.0
modify_font         cell_height 130%

include Catppuccin-Frappe.conf

enabled_layouts     tall:bias=60;full_size=2

tab_bar_min_tabs    1
tab_bar_edge        bottom
tab_bar_style       powerline
tab_powerline_style slanted
tab_title_template  {title}

map super+shift+enter new_window
map super+enter new_window_with_cwd

